attention_head_size: 1
categorical_groups: {}
causal_attention: true
dataset_parameters:
  add_encoder_length: false
  add_relative_time_idx: false
  add_target_scales: false
  allow_missing_timesteps: true
  categorical_encoders:
    __group_id__group: !!python/object:pytorch_forecasting.data.encoders.NaNLabelEncoder
      add_nan: false
      classes_:
        TATAMOTORS.NS: 0
      classes_vector_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - !!python/name:numpy.ndarray ''
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - !!python/object/apply:numpy.dtype
          args:
          - U13
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - 52
          - 4
          - 8
        - false
        - !!binary |
          VAAAAEEAAABUAAAAQQAAAE0AAABPAAAAVAAAAE8AAABSAAAAUwAAAC4AAABOAAAAUwAAAA==
      warn: true
  constant_fill_strategy: null
  group_ids:
  - group
  lags: null
  max_encoder_length: 90
  max_prediction_length: 30
  min_encoder_length: 90
  min_prediction_idx: !!python/object/apply:numpy._core.multiarray.scalar
  - !!python/object/apply:numpy.dtype
    args:
    - i8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    AAAAAAAAAAA=
  min_prediction_length: 30
  predict_mode: false
  randomize_length: null
  scalers:
    Volume: !!python/object:pytorch_forecasting.data.encoders.GroupNormalizer
      _groups: []
      _method_kwargs: {}
      center: true
      groups: null
      method: standard
      method_kwargs: {}
      norm_:
        center: !!python/object/apply:numpy._core.multiarray.scalar
        - &id001 !!python/object/apply:numpy.dtype
          args:
          - f8
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - -1
          - -1
          - 0
        - !!binary |
          zezem9vsmsI=
        scale: !!python/object/apply:numpy._core.multiarray.scalar
        - *id001
        - !!binary |
          Gi3Tih695EI=
      scale_by_group: false
      transformation: log
  static_categoricals: null
  static_reals: null
  target: Close
  target_normalizer: &id002 !!python/object:pytorch_forecasting.data.encoders.EncoderNormalizer
    _method_kwargs: {}
    center: true
    center_: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      0GUcaStpgUA=
    max_length: null
    method: standard
    method_kwargs: {}
    scale_: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      QP6zX8nqbUA=
    transformation: relu
  time_idx: time_idx
  time_varying_known_categoricals: null
  time_varying_known_reals: null
  time_varying_unknown_categoricals: null
  time_varying_unknown_reals:
  - Close
  - Volume
  variable_groups: null
  weight: null
dropout: 0.1
embedding_labels: {}
embedding_paddings: []
embedding_sizes: {}
hidden_continuous_size: 8
hidden_continuous_sizes: {}
hidden_size: 16
learning_rate: 0.03
log_gradient_flow: false
log_interval: -1
log_val_interval: null
lstm_layers: 1
mask_bias: -1000000000.0
max_encoder_length: 90
monotone_constaints: {}
monotone_constraints: {}
optimizer: adam
optimizer_params: null
output_size: 7
output_transformer: *id002
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 1000
reduce_on_plateau_reduction: 2.0
share_single_variable_networks: false
static_categoricals: []
static_reals: []
time_varying_categoricals_decoder: []
time_varying_categoricals_encoder: []
time_varying_reals_decoder: []
time_varying_reals_encoder:
- Close
- Volume
weight_decay: 0.0
x_categoricals: []
x_reals:
- Close
- Volume
